### ISSUE TITLE
Exception when depending on app with non-numeric characters in dependencies' versions

### ISSUE THREAD

**Issue by SLLCoding** [EnhancedMC/EnhancedMC#3]
Following stacktrace caused by version `0.1.0-SNAPSHOT`:
```
[21:41:25] [Client thread/ERROR] [EnhancedMC]: Error trying to read app: com.whodundid.enhancedmc.hotkeyapp.HotKeyApp@6c9dd79d! Ignoring...
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: java.lang.NumberFormatException: For input string: "0-SNAPSHOT"
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at java.lang.Integer.parseInt(Integer.java:580)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at java.lang.Integer.parseInt(Integer.java:615)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.whodundid.enhancedmc.core.app.AppLoader.loadApps(AppLoader.java:294)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.whodundid.enhancedmc.core.app.AppLoader.loadApps(AppLoader.java:218)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.whodundid.enhancedmc.core.EnhancedMC.postInit(EnhancedMC.java:115)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraft.client.Minecraft.startGame(Minecraft.java:532)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:360)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraft.client.main.Main.main(Main.java:116)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:95)
[21:41:25] [Client thread/INFO] [STDERR]: [com.whodundid.enhancedmc.core.app.AppLoader:loadApps:344]: 	at GradleStart.main(GradleStart.java:24)
```

**Comment by SLLCoding** [comment]
Fixed by ccf84b3
